name: koshudo
description: "甲州道中四十四次アプリ"
publish_to: none
version: 4.0.0+21

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  kaido_ui:
    path: ../../packages/kaido_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/pin/
    - assets/data/
    - assets/map/
    - assets/copyright/
    - assets/splash/
